[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/cdn-check"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "primeautobotz"
